export const initialOrder = {
  id: "999",
  orderId: "999",
  incrementId: "999",
  kamiounId: "999",
  state: "",
  status: "",
  total: 0,
  createdAt: 0,
  updatedAt: 0,
  deliveryDate: 0,
  customerId: "999",
  storeId: "999",
  customerPhone: "999",
  customerFirstname: "999",
  customerLastname: "999",
  deliveryAgentId: "",
  deliveryAgentName: "",
  deliverySlot: "999",

  deliveryStatus: "",
  source: "online",
  productsNames: [],
  items: [
    {
      id: "999",
      orderId: "999",
      productId: "999",
      productName: "",
      productPrice: "0",
      totalPrice: "0",
      quantity: "0",
      sku: "999",
      weight: "999",
    },
  ],
};
