import { axios } from "@/libs/axios";

export const editOrderDetails = async ({
  orderId,
  deliveryDate,
  items,
}: any): Promise<any> => {
  try {
    const data = {
      entity: {
        entity_id: orderId,
        extension_attributes: {
          delivery_date: deliveryDate,
        },
        items: items,
      },
    };
    await axios.magentoClient.put("orders/create", data);
  } catch (error) {
    process.env.NODE_ENV === "development" &&
      console.error("Error changing order status:", error);
    throw error;
  }
};

// const order =
//   // {
//   //   items: [
//   {
//     base_currency_code: "TND",
//     base_discount_amount: 0,
//     base_grand_total: 199.6,
//     base_discount_tax_compensation_amount: 0,
//     base_shipping_amount: 0,
//     base_shipping_discount_amount: 0,
//     base_shipping_discount_tax_compensation_amnt: 0,
//     base_shipping_incl_tax: 0,
//     base_shipping_tax_amount: 0,
//     base_subtotal: 199.6,
//     base_subtotal_incl_tax: 199.6,
//     base_tax_amount: 0,
//     base_total_due: 199.6,
//     base_to_global_rate: 1,
//     base_to_order_rate: 1,
//     billing_address_id: 126646,
//     created_at: "2024-07-11 13:29:10",
//     customer_email: "multiwcustomer@kamioun.com",
//     customer_firstname: "test",
//     customer_group_id: 3,
//     customer_id: 7390,
//     customer_is_guest: 0,
//     customer_lastname: "customer",
//     customer_note_notify: 1,
//     customer_taxvat: "000/AMCD/108222/T",
//     discount_amount: 0,
//     email_sent: 1,
//     entity_id: 63416,
//     global_currency_code: "TND",
//     grand_total: 199.6,
//     discount_tax_compensation_amount: 0,
//     increment_id: "000052622",
//     is_virtual: 0,
//     order_currency_code: "TND",
//     protect_code: "9b535b42345af5dadb26c241bfc48933",
//     quote_id: 81080,
//     remote_ip: "197.31.165.114",
//     shipping_amount: 0,
//     shipping_description: "Free Shipping - Free",
//     shipping_discount_amount: 0,
//     shipping_discount_tax_compensation_amount: 0,
//     shipping_incl_tax: 0,
//     shipping_tax_amount: 0,
//     state: "new",
//     status: "open",
//     store_currency_code: "TND",
//     store_id: 1,
//     store_name: "Main Website\nGrand Tunis\ndefault Store View",
//     store_to_base_rate: 0,
//     store_to_order_rate: 0,
//     subtotal: 199.6,
//     subtotal_incl_tax: 199.6,
//     tax_amount: 0,
//     total_due: 199.6,
//     total_item_count: 1,
//     total_qty_ordered: 4,
//     updated_at: "2024-07-11 13:29:38",
//     weight: 0,
//     items: [
//       {
//         amount_refunded: 0,
//         base_amount_refunded: 0,
//         base_cost: 46.9,
//         base_discount_amount: 0,
//         base_discount_invoiced: 0,
//         base_discount_tax_compensation_amount: 0,
//         base_original_price: 49.9,
//         base_price: 49.9,
//         base_price_incl_tax: 49.9,
//         base_row_invoiced: 0,
//         base_row_total: 199.6,
//         base_row_total_incl_tax: 199.6,
//         base_tax_amount: 0,
//         base_tax_invoiced: 0,
//         created_at: "2024-07-11 13:29:10",
//         discount_amount: 0,
//         discount_invoiced: 0,
//         discount_percent: 0,
//         free_shipping: 0,
//         discount_tax_compensation_amount: 0,
//         is_qty_decimal: 0,
//         is_virtual: 0,
//         item_id: 797356,
//         name: "Sicam - Tomate entière pelée 1/2",
//         no_discount: 0,
//         order_id: 63416,
//         original_price: 49.9,
//         price: 49.9,
//         price_incl_tax: 49.9,
//         product_id: 1967,
//         product_type: "simple",
//         qty_canceled: 0,
//         qty_invoiced: 0,
//         qty_ordered: 4,
//         qty_refunded: 0,
//         qty_shipped: 0,
//         quote_item_id: 1246825,
//         row_invoiced: 0,
//         row_total: 199.6,
//         row_total_incl_tax: 199.6,
//         row_weight: 0,
//         sku: "012-012282",
//         store_id: 1,
//         tax_amount: 0,
//         tax_invoiced: 0,
//         tax_percent: 0,
//         updated_at: "2024-07-11 13:29:11",
//         weight: 4,
//       },
//     ],
//     billing_address: {
//       address_type: "billing",
//       city: "Tunis",
//       country_id: "TN",
//       email: "7390-7390-2574@kamioun.tn",
//       entity_id: 126646,
//       firstname: "test",
//       lastname: "customer",
//       parent_id: 63416,
//       postcode: "1000",
//       region: "TEST",
//       region_code: "TEST",
//       street: ["Avenue De TEST"],
//       telephone: "00123456",
//     },
//     payment: {
//       account_status: null,
//       additional_information: ["Check / Money order"],
//       amount_ordered: 199.6,
//       base_amount_ordered: 199.6,
//       base_shipping_amount: 0,
//       cc_last4: null,
//       entity_id: 63324,
//       method: "checkmo",
//       parent_id: 63416,
//       shipping_amount: 0,
//     },
//     status_histories: [
//       {
//         comment:
//           "&lt;tr&gt;&lt;th&gt;API LOG&lt;/th&gt;&lt;th&gt;KamiounOrderId&lt;/th&gt;&lt;th&gt;OOS&lt;/th&gt;&lt;th&gt;LoyaltyPointValue&lt;/th&gt;&lt;th&gt;DeliveryDate&lt;/th&gt;&lt;th&gt;FromMobile&lt;/th&gt;&lt;th&gt;Verified&lt;/th&gt;&lt;th&gt;JustCreated&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Old&lt;/td&gt;&lt;td&gt;52622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 - Sicam - Tomate enti&egrave;re pel&eacute;e 1/2 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;New&lt;/td&gt;&lt;td&gt;000052622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;#kamioun#order#log",
//         created_at: "2024-07-11 13:30:43",
//         entity_id: 665897,
//         entity_name: "order",
//         is_customer_notified: 0,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//       {
//         comment:
//           "&lt;tr&gt;&lt;th&gt;API LOG&lt;/th&gt;&lt;th&gt;KamiounOrderId&lt;/th&gt;&lt;th&gt;OOS&lt;/th&gt;&lt;th&gt;LoyaltyPointValue&lt;/th&gt;&lt;th&gt;DeliveryDate&lt;/th&gt;&lt;th&gt;FromMobile&lt;/th&gt;&lt;th&gt;Verified&lt;/th&gt;&lt;th&gt;JustCreated&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Old&lt;/td&gt;&lt;td&gt;52622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 - Sicam - Tomate enti&egrave;re pel&eacute;e 1/2 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;New&lt;/td&gt;&lt;td&gt;000052622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;#kamioun#order#log",
//         created_at: "2024-07-11 13:29:38",
//         entity_id: 665896,
//         entity_name: "order",
//         is_customer_notified: 0,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//       {
//         comment:
//           "&lt;tr&gt;&lt;th&gt;API LOG&lt;/th&gt;&lt;th&gt;KamiounOrderId&lt;/th&gt;&lt;th&gt;OOS&lt;/th&gt;&lt;th&gt;LoyaltyPointValue&lt;/th&gt;&lt;th&gt;DeliveryDate&lt;/th&gt;&lt;th&gt;FromMobile&lt;/th&gt;&lt;th&gt;Verified&lt;/th&gt;&lt;th&gt;JustCreated&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Old&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 - Sicam - Tomate enti&egrave;re pel&eacute;e 1/2 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;New&lt;/td&gt;&lt;td&gt;000052622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;#kamioun#order#log",
//         created_at: "2024-07-11 13:29:38",
//         entity_id: 665895,
//         entity_name: "order",
//         is_customer_notified: 0,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//       {
//         comment:
//           "&lt;tr&gt;&lt;th&gt;API LOG&lt;/th&gt;&lt;th&gt;OOS&lt;/th&gt;&lt;th&gt;DeliveryDate&lt;/th&gt;&lt;th&gt;FromMobile&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Old&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 - Sicam - Tomate enti&egrave;re pel&eacute;e 1/2 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;New&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;2024-07-22&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;#kamioun#order#log",
//         created_at: "2024-07-11 13:29:13",
//         entity_id: 665894,
//         entity_name: "order",
//         is_customer_notified: 0,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//       {
//         comment:
//           "&lt;tr&gt;&lt;th&gt;API LOG&lt;/th&gt;&lt;th&gt;KamiounOrderId&lt;/th&gt;&lt;th&gt;OOS&lt;/th&gt;&lt;th&gt;LoyaltyPointValue&lt;/th&gt;&lt;th&gt;FromMobile&lt;/th&gt;&lt;th&gt;JustCreated&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Old&lt;/td&gt;&lt;td&gt;52622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 - Sicam - Tomate enti&egrave;re pel&eacute;e 1/2 : &lt;/b&gt;4.0000&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;New&lt;/td&gt;&lt;td&gt;000052622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 : &lt;/b&gt;4&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;#kamioun#order#log",
//         created_at: "2024-07-11 13:29:12",
//         entity_id: 665893,
//         entity_name: "order",
//         is_customer_notified: 0,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//       {
//         comment:
//           "&lt;tr&gt;&lt;th&gt;API LOG&lt;/th&gt;&lt;th&gt;KamiounOrderId&lt;/th&gt;&lt;th&gt;OOS&lt;/th&gt;&lt;th&gt;LoyaltyPointValue&lt;/th&gt;&lt;th&gt;FromMobile&lt;/th&gt;&lt;th&gt;JustCreated&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;Old&lt;/td&gt;&lt;td&gt;52622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 - Sicam - Tomate enti&egrave;re pel&eacute;e 1/2 : &lt;/b&gt;&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;New&lt;/td&gt;&lt;td&gt;000052622&lt;/td&gt;&lt;td&gt;&lt;b&gt;797356 : &lt;/b&gt;4&lt;br&gt;&lt;/td&gt;&lt;td&gt;399&lt;/td&gt;&lt;td&gt;1&lt;/td&gt;&lt;td&gt;no&lt;/td&gt;&lt;td&gt;&lt;/td&gt;&lt;/tr&gt;#kamioun#order#log",
//         created_at: "2024-07-11 13:29:11",
//         entity_id: 665892,
//         entity_name: "order",
//         is_customer_notified: 0,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//       {
//         comment: null,
//         created_at: "2024-07-11 13:29:10",
//         entity_id: 665891,
//         entity_name: "order",
//         is_customer_notified: 1,
//         is_visible_on_front: 0,
//         parent_id: 63416,
//         status: "open",
//       },
//     ],
//     extension_attributes: {
//       shipping_assignments: [
//         {
//           shipping: {
//             address: {
//               address_type: "shipping",
//               city: "Tunis",
//               country_id: "TN",
//               email: "7390-7390-2574@kamioun.tn",
//               entity_id: 126645,
//               firstname: "test",
//               lastname: "customer",
//               parent_id: 63416,
//               postcode: "1000",
//               region: "TEST",
//               region_code: "TEST",
//               street: ["Avenue De TEST"],
//               telephone: "00123456",
//             },
//             method: "freeshipping_freeshipping",
//             total: {
//               base_shipping_amount: 0,
//               base_shipping_discount_amount: 0,
//               base_shipping_discount_tax_compensation_amnt: 0,
//               base_shipping_incl_tax: 0,
//               base_shipping_tax_amount: 0,
//               shipping_amount: 0,
//               shipping_discount_amount: 0,
//               shipping_discount_tax_compensation_amount: 0,
//               shipping_incl_tax: 0,
//               shipping_tax_amount: 0,
//             },
//           },
//           items: [
//             {
//               amount_refunded: 0,
//               base_amount_refunded: 0,
//               base_cost: 46.9,
//               base_discount_amount: 0,
//               base_discount_invoiced: 0,
//               base_discount_tax_compensation_amount: 0,
//               base_original_price: 49.9,
//               base_price: 49.9,
//               base_price_incl_tax: 49.9,
//               base_row_invoiced: 0,
//               base_row_total: 199.6,
//               base_row_total_incl_tax: 199.6,
//               base_tax_amount: 0,
//               base_tax_invoiced: 0,
//               created_at: "2024-07-11 13:29:10",
//               discount_amount: 0,
//               discount_invoiced: 0,
//               discount_percent: 0,
//               free_shipping: 0,
//               discount_tax_compensation_amount: 0,
//               is_qty_decimal: 0,
//               is_virtual: 0,
//               item_id: 797356,
//               name: "Sicam - Tomate entière pelée 1/2",
//               no_discount: 0,
//               order_id: 63416,
//               original_price: 49.9,
//               price: 49.9,
//               price_incl_tax: 49.9,
//               product_id: 1967,
//               product_type: "simple",
//               qty_canceled: 0,
//               qty_invoiced: 0,
//               qty_ordered: 4,
//               qty_refunded: 0,
//               qty_shipped: 0,
//               quote_item_id: 1246825,
//               row_invoiced: 0,
//               row_total: 199.6,
//               row_total_incl_tax: 199.6,
//               row_weight: 0,
//               sku: "012-012282",
//               store_id: 1,
//               tax_amount: 0,
//               tax_invoiced: 0,
//               tax_percent: 0,
//               updated_at: "2024-07-11 13:29:11",
//               weight: 4,
//             },
//           ],
//         },
//       ],
//       payment_additional_info: [
//         {
//           key: "method_title",
//           value: "Check / Money order",
//         },
//       ],
//       applied_taxes: [],
//       item_applied_taxes: [],
//       loyalty_point_value: 399,
//       delivery_date: "2024-07-22",
//       just_created: "no",
//       from_mobile: 1,
//       verified: 1,
//       kamioun_order_id: 52622,
//     },
//   };
//   ],
//   search_criteria: {
//     filter_groups: [],
//     sort_orders: [
//       {
//         field: "entity_id",
//         direction: "DESC",
//       },
//     ],
//     page_size: 1,
//     current_page: 1,
//   },
//   total_count: 62191,
// };
