export const rows = [
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
  [
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
    { cell: <div className="flex h-12 items-center justify-center">test</div> },
  ],
];
